name: POPF

on:
  pull_request:
  push:
    branches:
      - ros2
      
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    steps:
      - name: log untrusted output
        run: |

          # disable command workflow processing
          echo "::stop-commands::`echo -n ${{ github.token }} | sha256sum | head -c 64`"

          # log untrusted output
          echo "untrusted output"

          # enable workflow command processing
          echo "::`echo -n ${{ github.token }} | sha256sum | head -c 64`::"
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.0.25
        with:
          required-ros-distributions: foxy
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.1.0
        with:
          package-name: popf
          target-ros2-distro: ${{ matrix.os }}
          vcs-repo-file-url: ""
